### ISSUE TITLE
Create Symbol Mark

### ISSUE THREAD

**Issue by atepoorthuis** [spatialnetworkslab/vue-gg#21]
Similar to: https://vega.github.io/vega/docs/marks/symbol/

**Comment by atepoorthuis** [comment]
With @GraceGSy's [work on this](https://github.com/spatialnetworkslab/vue-gg/tree/symbolMark) should we just remove the older `Point` Mark since the `Symbol` mark has that capability as well?

**Comment by GraceGSy** [comment]
I think that's a good idea, especially since symbol defaults to circle/point anyway.

One thing to consider: the point mark uses the `radius` prop, which makes sense for points, but symbol uses `size` since radius doesn't make sense in context of, say, triangles. I'm not sure if we want to switch completely over to sizeor whether we just want to provide both props.

**Comment by atepoorthuis** [comment]
I think it's fine with just `size`. For circles, size == diameter and if you want to set by radius just divide/multiply by 2. If you want to make the circles proportional to some data attribute, you'd probably want to use area (not radius) anyways, and even that is [problematic](https://makingmaps.net/2007/08/28/perceptual-scaling-of-map-symbols/).

**Comment by luucvanderzee** [comment]
I think this is fine, but maybe we could just add the `vgg-point` tag anyway, since it seems like a convenient shorthand. The logic/implementation would be in the `vgg-symbol` component, with the `vgg-point` just being a `vgg-symbol` with a point as default shape.

Also, you could make the argument that there is a difference between a point and a circle... a point is just an infinitely small indicator of location that has a `radius` just to make it observable to us, while the circle is an actual 2d object that happens to be round, if that makes any sense. So following this logic you would for example draw the point always in exactly the same way, while you would draw the circle differently in different coordinate systems.

But then again, I don't know if we would even really need a circle mark...

**Comment by atepoorthuis** [comment]
Done in #44.
